apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: backend-tests-go-ijvngrao
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/backend-tests-go-ijvngrao:1baf5c14c913989e6baba4c66e4d2c3c731325d0@sha256:6ade1a4876d7a9a68f7485caffab50eedb1593f1c5356c2f566ce53e024dfbca
        name: container-image  
